name: First workflow

on:
  push:
    branches:
      -  main

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print a welcome message
        run: echo "Welocme to our first Github Actions Workflow!"

      - name: Checkout Repository
        uses: actions/checkout@v7.0.0

      - name: list repo files
        run: ls -la
